# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target 'Film' do
pod 'AFNetworking', '~> 2.6.0'


end

target 'FilmTests' do

end

target 'FilmUITests' do

end

